import type { PagesFunction } from '@cloudflare/workers-types';
interface Env { sph_management_db: D1Database }
const allowed = new Set(['sph','design_items','sales','profiles','user_roles']);
const jsonColumns = new Set(['specs','items','payments','terms','payments','designs','include_ppn']);
async function auth(request: Request, env: Env) { const sid=(request.headers.get('cookie')||'').match(/(?:^|; )sph_session=([^;]+)/)?.[1]; if(!sid)return null; return env.sph_management_db.prepare('SELECT user_id FROM app_sessions WHERE id=? AND expires_at>?').bind(sid,new Date().toISOString()).first<{user_id:string}>(); }
export const onRequest: PagesFunction<Env> = async ({request,env}) => {
 const session=await auth(request,env); if(!session)return Response.json({error:'Unauthorized'},{status:401});
 const url=new URL(request.url), table=url.searchParams.get('table')||''; if(!allowed.has(table))return Response.json({error:'Invalid table'},{status:400});
 const id=url.searchParams.get('id');
 if(request.method==='GET'){let sql=`SELECT * FROM ${table}`, params:string[]=[]; if(table==='sph'&&id){sql+=' WHERE id=?';params=[id]} else if(table==='sph'&&url.searchParams.get('status')){sql+=' WHERE status=?';params=[url.searchParams.get('status')!]} else sql+=' ORDER BY created_at DESC'; const result=await env.sph_management_db.prepare(sql).bind(...params).all(); const data=(result.results||[]).map((row:any)=>{const out={...row};for(const k of jsonColumns)if(typeof out[k]==='string')try{out[k]=JSON.parse(out[k])}catch{} return out});return Response.json({data});}
 if(request.method==='POST'||request.method==='PUT'){const body=await request.json() as Record<string,unknown>; const clean=Object.fromEntries(Object.entries(body).filter(([k])=>!['id','created_at','updated_at'].includes(k)).map(([k,v])=>[k,jsonColumns.has(k)&&typeof v!=='string'?JSON.stringify(v):v])); if(request.method==='PUT'&&!id)return Response.json({error:'id required'},{status:400}); if(request.method==='PUT'){const entries=Object.entries(clean);await env.sph_management_db.prepare(`UPDATE ${table} SET ${entries.map(([k])=>`${k}=?`).join(',')}, updated_at=? WHERE id=?`).bind(...entries.map(([,v])=>v),new Date().toISOString(),id).run();}else{const newId=crypto.randomUUID(), entries=Object.entries({...clean,id:newId,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});await env.sph_management_db.prepare(`INSERT INTO ${table} (${entries.map(([k])=>k).join(',')}) VALUES (${entries.map(()=>'?').join(',')})`).bind(...entries.map(([,v])=>v)).run();}return Response.json({ok:true});}
 if(request.method==='DELETE'){if(!id)return Response.json({error:'id required'},{status:400});await env.sph_management_db.prepare(`DELETE FROM ${table} WHERE id=?`).bind(id).run();return Response.json({ok:true});}
 return new Response('Method Not Allowed',{status:405});
};
