import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Trash2, Check, X, Ban, RotateCcw } from 'lucide-react';
import { toast } from 'sonner';

type Account={id:string;email:string;full_name:string;role:string;status:string;created_at:string};
export default function AdminUsers(){const [users,setUsers]=useState<Account[]>([]);const load=()=>fetch('/api/admin/users').then(r=>r.json()).then(d=>setUsers(d.data||[]));useEffect(()=>{load()},[]);const update=async(id:string,p:any)=>{const r=await fetch(`/api/admin/users?id=${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)return toast.error(d.error||'Gagal memperbarui');toast.success('Akun diperbarui');load()};const remove=async(id:string)=>{if(!confirm('Hapus akun ini?'))return;await fetch(`/api/admin/users?id=${id}`,{method:'DELETE'});toast.success('Akun dihapus');load()};return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Manajemen Akun</h1><p className="text-muted-foreground">Setujui, tolak, nonaktifkan, ubah role, atau hapus akun.</p></div><div className="rounded-lg border bg-card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-4">Akun</th><th className="p-4">Status</th><th className="p-4">Role</th><th className="p-4">Dibuat</th><th className="p-4">Aksi</th></tr></thead><tbody>{users.map(u=><tr className="border-b last:border-0" key={u.id}><td className="p-4"><b>{u.full_name||'-'}</b><div className="text-muted-foreground">{u.email}</div></td><td className="p-4"><Badge variant={u.status==='approved'?'default':'secondary'}>{u.status}</Badge></td><td className="p-4"><Select value={u.role} onValueChange={role=>update(u.id,{role})}><SelectTrigger className="w-28"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="staff">Staff</SelectItem><SelectItem value="admin">Admin</SelectItem></SelectContent></Select></td><td className="p-4">{new Date(u.created_at).toLocaleDateString('id-ID')}</td><td className="p-4 flex gap-2">{u.status==='pending'&&<><Button size="sm" onClick={()=>update(u.id,{status:'approved'})}><Check className="w-4"/></Button><Button size="sm" variant="outline" onClick={()=>update(u.id,{status:'rejected'})}><X className="w-4"/></Button></>}{u.status==='approved'&&<Button size="sm" variant="outline" onClick={()=>update(u.id,{status:'disabled'})}><Ban className="w-4"/></Button>}{u.status==='disabled'&&<Button size="sm" variant="outline" onClick={()=>update(u.id,{status:'approved'})}><RotateCcw className="w-4"/></Button>}<Button size="sm" variant="destructive" onClick={()=>remove(u.id)}><Trash2 className="w-4"/></Button></td></tr>)}</tbody></table></div></div>}
